

Alger = [
    "BAB EL OUED", "BOLOGHINE IBNOU ZIRI", "CASBAH", "OUED KORICHE", "RAIS HAMIDOU",
    "BARAKI", "LES EUCALYPTUS", "SIDI MOUSSA",
    "BIR MOURAD RAIS", "BIRKHADEM", "DJASR KASENTINA", "HYDRA", "SEHAOULA",
    "BIR TOUTA", "OULED CHEBEL", "TESSALA EL MERDJA",
    "BEN AKNOUN", "BENI MESSOUS", "BOUZAREAH", "EL BIAR",
    "AIN BENIAN", "CHERAGA", "DELY IBRAHIM", "HAMMAMET", "OULED FAYET",
    "AIN TAYA", "BAB EZZOUAR", "BORDJ EL BAHRI", "BORDJ EL KIFFAN", "DAR EL BEIDA",
    "EL MARSA", "MOHAMMADIA",
    "BABA HASSEN", "DOUIRA", "DRARIA", "EL ACHOUR", "KHRAISSIA",
    "BACHEDJERAH", "BOUROUBA", "EL HARRACH", "OUED SMAR",
    "EL MAGHARIA", "HUSSEIN DEY", "KOUBA", "MOHAMED BELOUZDAD",
    "HERRAOUA", "REGHAIA", "ROUIBA",
    "ALGER CENTRE", "EL MADANIA", "EL MOURADIA", "SIDI M'HAMED",
    "MAALMA", "RAHMANIA", "SOUIDANIA", "STAOUELI", "ZERALDA"
]

Annaba = ['SIDI AMAR','EL HADJAR','EL BOUNI','CHETAIBI',
          'TREAT','OUED EL ANEB','OUED EL ANEB','BERRAHAL','SERAIDI','ANNABA','EL EULMA','CHEURFA','AIN EL BERDA'
]

Oran = [


]



custom = [
    "BIR MOURAD RAIS",
    "BIRKHADEM",
    "DJASR KASENTINA",
    "HYDRA",
    "SEHAOULA",
    "KOUBA"
    ]